module NoShitInMyGreenDots
  VERSION: String

  def self.enable!: (?Symbol framework) -> void
  def self.capture_stdout: () { () -> untyped } -> String
  def self.leak_message: (String) -> String
end
