module NoShitInMyGreenDots
  VERSION: String

  def self.enable!: (?Symbol framework) -> void
  def self.for_minitest!: () -> void
  def self.for_rspec!: () -> void
  def self.enabled?: (?Symbol framework) -> bool
  def self.capture_stdout: () { () -> untyped } -> String
  def self.leak_message: (String) -> String
end
